---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: 4-example
spec:
  replicas: 5 # 这里配置了很大的pod副本数，以便让pod填满当前的node，出发新node的autoscaling
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: aputra/myapp-195:v2
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests: # 为了测试cluster worker node的auto scaling功能，这里配置了很大的内存和cpu需求
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m