---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: 12-example
  annotations:
    # 这里配置上我们通过terraform创建的role的arn
    eks.amazonaws.com/role-arn: arn:aws:iam::228717161587:role/staging-demo-myapp-secrets