# 让cluster中，或者cluster外部可以访问redis的服务
apiVersion: v1
kind: Service
metadata:
  name: redis-access-service-0
  namespace: redis-cluster
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing  # 公开访问
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp    # 使用TCP协议
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip      # 目标类型为IP
  labels:
    app: redis
spec:
  type: LoadBalancer
  ports:
  - name: redis-port
    protocol: "TCP"
    port: 6379
    targetPort: 6379
  - name: bus-port
    protocol: "TCP"
    port: 16379 
    targetPort: 16379 
  selector:
    statefulset.kubernetes.io/pod-name: redis-0 # 指定为第几个pod创建NLB